name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        env:
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          REACT_APP_GITHUB_CLIENT_SECRET: ${{ secrets.REACT_APP_GITHUB_CLIENT_SECRET }}
          REACT_APP_REPO_TOKEN: ${{ secrets.REACT_APP_REPO_TOKEN }}
        run: npm run build
      
      - name: Download existing tokens
        run: |
          mkdir -p build/tokens
          if curl -s "https://shreyas-m-246418.github.io/spa-gh/tokens/" > /dev/null; then
            wget -r -np -nH --cut-dirs=2 -P build/tokens https://shreyas-m-246418.github.io/spa-gh/tokens/
          fi
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build