name: Generate OAuth Tokens

on:
  repository_dispatch:
    types: [oauth-code]

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create tokens directory
        run: mkdir -p tokens
      
      - name: Exchange code for token
        env:
          CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REACT_APP_GITHUB_CLIENT_SECRET }}
          CODE: ${{ github.event.client_payload.code }}
        run: |
          token_response=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"$CODE\"}" \
            "https://github.com/login/oauth/access_token")
          echo "$token_response" > "tokens/$CODE.json"
      
      - name: Deploy token file
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: tokens
          target-folder: tokens
          clean: false