name: Generate OAuth Tokens

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  generate-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create tokens directory
        run: mkdir -p build/tokens
      
      - name: Exchange code for token
        env:
          CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REACT_APP_GITHUB_CLIENT_SECRET }}
        run: |
          for code in $(curl -s "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | jq -r '.[].title | select(startswith("auth_"))'); do
            token_response=$(curl -s -X POST \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              -d "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"${code#auth_}\"}" \
              "https://github.com/login/oauth/access_token")
            
            echo "$token_response" > "build/tokens/${code#auth_}.json"
          done
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          clean: false  # Don't remove existing files 